SET @INV := '16912192052659234517';

SELECT 'lg_ZONE_GEO_ID'        AS colonne, COUNT(*) AS produits_orphelins FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_ZONE_GEO_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_zone_geographique r WHERE r.lg_ZONE_GEO_ID=f.lg_ZONE_GEO_ID)
UNION ALL SELECT 'lg_GROSSISTE_ID', COUNT(*) FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_GROSSISTE_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_grossiste r WHERE r.lg_GROSSISTE_ID=f.lg_GROSSISTE_ID)
UNION ALL SELECT 'lg_FAMILLEARTICLE_ID', COUNT(*) FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_FAMILLEARTICLE_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_famillearticle r WHERE r.lg_FAMILLEARTICLE_ID=f.lg_FAMILLEARTICLE_ID)
UNION ALL SELECT 'lg_CODE_TVA_ID', COUNT(*) FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_CODE_TVA_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_code_tva r WHERE r.lg_CODE_TVA_ID=f.lg_CODE_TVA_ID)
UNION ALL SELECT 'lg_CODE_ACTE_ID', COUNT(*) FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_CODE_ACTE_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_code_acte r WHERE r.lg_CODE_ACTE_ID=f.lg_CODE_ACTE_ID)
UNION ALL SELECT 'lg_CODE_GESTION_ID', COUNT(*) FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_CODE_GESTION_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_code_gestion r WHERE r.lg_CODE_GESTION_ID=f.lg_CODE_GESTION_ID)
UNION ALL SELECT 'lg_FORME_ID', COUNT(*) FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_FORME_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_forme_article r WHERE r.lg_FORME_ARTICLE_ID=f.lg_FORME_ID)
UNION ALL SELECT 'lg_FABRIQUANT_ID', COUNT(*) FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_FABRIQUANT_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_fabriquant r WHERE r.lg_FABRIQUANT_ID=f.lg_FABRIQUANT_ID)
UNION ALL SELECT 'lg_REMISE_ID', COUNT(*) FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_REMISE_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_remise r WHERE r.lg_REMISE_ID=f.lg_REMISE_ID)
UNION ALL SELECT 'lg_TYPEETIQUETTE_ID', COUNT(*) FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_TYPEETIQUETTE_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_typeetiquette r WHERE r.lg_TYPEETIQUETTE_ID=f.lg_TYPEETIQUETTE_ID)
UNION ALL SELECT 'lg_INDICATEUR_REAPPRO', COUNT(*) FROM t_inventaire_famille t JOIN t_famille f ON f.lg_FAMILLE_ID=t.lg_FAMILLE_ID
  WHERE t.lg_INVENTAIRE_ID=@INV AND f.lg_INDICATEUR_REAPPROVISIONNEMENT_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_indicateur_reapprovisionnement r WHERE r.lg_INDICATEUR_REAPPROVISIONNEMENT_ID=f.lg_INDICATEUR_REAPPROVISIONNEMENT_ID)
UNION ALL SELECT 'lg_FAMILLE_STOCK_ID', COUNT(*) FROM t_inventaire_famille t
  WHERE t.lg_INVENTAIRE_ID=@INV AND t.lg_FAMILLE_STOCK_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_famille_stock r WHERE r.lg_FAMILLE_STOCK_ID=t.lg_FAMILLE_STOCK_ID);
