# -*- coding: utf-8 -*-
"""Contenu du cahier de recette de la branche claude/new-session-xm8ptu.

Chaque cas est (numero, ecran, action, attendu, reference).
Une entree ('SECTION', titre) ouvre une section.
"""

CAS = [
 ('SECTION', 'A. PRÉREQUIS AVANT LA RECETTE'),
 ('A1', 'Déploiement', "Déployer le WAR de la branche, puis consulter le journal du serveur.",
  "Les migrations V6.9.35 à V6.9.49 sont passées, toutes en succès. Aucune migration en échec dans flyway_schema_history.",
  'V6.9.35 → V6.9.49'),
 ('A2', 'Configuration Posos', "Ouvrir le dossier qui contient dicisms.properties (sous Windows : D:\\prestige\\config, ou <profil>\\Documents).",
  "Le fichier posos.properties y a été créé tout seul, avec ses clés vides et ses explications. Il n'écrase jamais un fichier déjà renseigné.",
  '7a2b800'),
 ('A3', 'Privilèges', "Écran des rôles : chercher les privilèges P_SM_DEPOT_EXTENSION, P_DEPOT_EXT_VALORISATION, P_VENTE_DEPOT_EXTENSION, P_DEPOT_EXT_CA, P_DEPOT_EXT_POINT_CAISSE, P_SM_POSOS, P_IMPORT_CLIENTS.",
  "Les sept privilèges existent et sont attribuables rôle par rôle. Les quatre privilèges d'onglet sont détenus par tous les rôles qui peuvent ouvrir « Gestion depots extensions » : personne ne perd d'onglet à la livraison.",
  'V6.9.46, V6.9.49'),
 ('A4', 'Menu', "Dérouler la rubrique GESTION DES TIERS-PAYANTS.",
  "Le menu « Gestion depots extensions » y figure (il était dans GESTION DU STOCK). Son libellé et sa description tiennent dans la navigation, sans être coupés.",
  'V6.9.49, V6.9.47'),
 ('A5', 'Jeu d\'essai', "Disposer d'au moins un dépôt d'extension actif, avec du stock : quelques articles à stock positif, un à zéro, un à stock négatif, et des articles dans plusieurs rayons.",
  "Sans ce jeu d'essai, les cas C5 à C10 (couleurs et filtres) ne sont pas vérifiables.",
  '—'),

 ('SECTION', 'B. GESTION DÉPÔTS EXTENSIONS — ÉCRAN ET ONGLETS'),
 ('B1', 'Ouverture', "Ouvrir le menu « Gestion depots extensions ».",
  "L'écran s'ouvre sur l'onglet « Saisir vente dépôt », qui est le PREMIER onglet. Quatre onglets : Saisir vente dépôt, Valorisation, Chiffre d'affaires, Point de caisse.",
  'd1ec13e'),
 ('B2', 'Couleurs', "Regarder les quatre onglets.",
  "Chaque onglet porte sa couleur : vert (saisie de vente), bleu (valorisation), orange (chiffre d'affaires), violet (point de caisse). L'onglet actif a un fond teinté et son libellé en gras.",
  'd1ec13e'),
 ('B3', 'Sélection du dépôt', "Choisir un dépôt dans le sélecteur en haut de l'écran.",
  "Un SEUL sélecteur pilote tout l'écran. La liste ne propose que des dépôts d'extension actifs — jamais l'officine.",
  '647702e'),
 ('B4', 'Sans dépôt choisi', "Ouvrir l'écran sans rien choisir, puis passer sur l'onglet Valorisation.",
  "Rien n'est demandé au serveur, la liste est vide, les boutons d'édition sont inactifs, et le message invite à choisir un dépôt.",
  'adc587e'),
 ('B5', 'Changement de dépôt', "Choisir un dépôt, attendre l'affichage, puis choisir un autre dépôt.",
  "Les listes se vident avant de recharger : on ne voit jamais, même une seconde, le contenu du dépôt précédent sous le nom du nouveau.",
  '647702e'),
 ('B6', 'Privilège par onglet', "Retirer P_DEPOT_EXT_CA à votre rôle, se DÉCONNECTER puis se reconnecter, rouvrir l'écran.",
  "L'onglet Chiffre d'affaires a disparu (retiré, pas grisé). L'écran s'ouvre sur un onglet existant et reste utilisable. Remettre le privilège ensuite.",
  'd1ec13e'),
 ('B7', 'Privilège côté serveur', "Sans le privilège P_DEPOT_EXT_CA, appeler directement api/v1/depot-extension/ca (ou .../ca/pdf) depuis le navigateur.",
  "Le service REFUSE : « Votre profil ne donne pas accès à cette partie de l'écran » (et 403 pour l'édition). Masquer un onglet n'est pas un contrôle d'accès.",
  'd1ec13e'),

 ('SECTION', 'C. ONGLET VALORISATION — LISTE DES ARTICLES'),
 ('C1', 'Nom des vues', "Onglet Valorisation : lire les deux boutons de bascule.",
  "Ils s'appellent « Liste des articles » et « Valorisation par emplacement » (et non plus « valorisation simple » / « par emplacement »).",
  '28b590f'),
 ('C2', 'État de départ', "Choisir un dépôt et regarder la barre de critères.",
  "La case « masquer les articles à 0 » est DÉCOCHÉE, et le filtre Stock est sur « Tous » : la liste complète s'affiche dès l'arrivée.",
  '28b590f'),
 ('C3', 'Valorisation affichée', "Lire la ligne de valorisation au-dessus de la liste.",
  "Elle nomme le dépôt, le nombre d'articles, les unités, la valeur d'achat et la valeur de vente. Elle porte sur TOUTES les lignes retenues, pas sur la page affichée : changer de page ne la modifie pas.",
  'adc587e'),
 ('C4', 'Colonnes', "Parcourir les colonnes de la liste.",
  "CIP, Désignation, Famille, Emplacement, Stock dépôt, PA, PV, Valeur achat, Valeur vente. Chaque ligne porte son propre calcul.",
  'adc587e'),
 ('C5', 'Stock négatif en rouge', "Repérer un article au stock négatif.",
  "Toute la LIGNE est en rouge, sur un fond très pâle — pas seulement la case du stock. Une légende sous la liste rappelle le code couleur.",
  '28b590f'),
 ('C6', 'Stock à zéro en violet', "Repérer un article au stock zéro.",
  "Toute la ligne est en violet. Cliquer dessus GARDE la couleur : la sélection n'effacera pas l'information.",
  '28b590f'),
 ('C7', 'Masquer les articles à 0', "Cocher « masquer les articles à 0 ».",
  "Les lignes à zéro disparaissent. Le stock NÉGATIF reste visible : c'est une anomalie à voir, pas un article absent.",
  '28b590f'),
 ('C8', 'Filtre sur le stock', "Choisir successivement Négatif, À zéro, Positif dans le filtre Stock.",
  "Chaque choix ne garde que les lignes correspondantes. Le nombre total et la valorisation suivent à chaque fois.",
  '28b590f'),
 ('C9', 'Pas de critère contradictoire', "Choisir un filtre Stock autre que « Tous ».",
  "La case « masquer les articles à 0 » devient GRISÉE : le filtre décide. Revenir à « Tous » la rend de nouveau utilisable.",
  '28b590f'),
 ('C10', 'Filtre emplacement', "Choisir un rayon dans le filtre Emplacement (à côté du filtre Famille).",
  "Seuls les articles de ce RAYON restent. Attention : c'est bien le rayon de l'article, le dépôt étant déjà choisi en haut.",
  '28b590f'),
 ('C11', 'Recherche', "Saisir un CIP ou un début de désignation, puis Entrée ou Rechercher.",
  "Seuls les articles correspondants restent, et la valorisation ne porte plus que sur eux.",
  'adc587e'),
 ('C12', 'Export Excel', "Cliquer « Exporter Excel ».",
  "Le fichier se télécharge, nommé d'après le dépôt (stock_depot_<DEPOT>.xls), et porte les critères appliqués.",
  'adc587e'),
 ('C13', 'Édition PDF', "Cliquer « Imprimer » depuis la liste des articles.",
  "Le PDF s'ouvre DANS un onglet du navigateur (aucune fenêtre surgissante, aucun téléchargement). Il nomme le dépôt, rappelle les critères avec les mots de l'écran, et porte les colonnes de stock et de valorisation.",
  'adc587e'),
 ('C14', 'Pagination du PDF', "Faire défiler le PDF jusqu'à la dernière page.",
  "Chaque page porte « Page X / Y », la date, l'opérateur, et le rappel que la liste est triée par emplacement.",
  '28b590f'),

 ('SECTION', 'D. ONGLET VALORISATION — PAR EMPLACEMENT'),
 ('D1', 'Ventilation', "Cliquer « Valorisation par emplacement ».",
  "Une ligne par rayon, avec RÉFÉRENCES, UNITÉS, valeur d'achat et valeur de vente. Les articles sans rayon sont regroupés sous « Sans emplacement » — leur valeur n'est pas perdue.",
  '647702e'),
 ('D2', 'Deux grandeurs distinctes', "Survoler les en-têtes RÉFÉRENCES et UNITÉS.",
  "Les infobulles disent la différence : RÉFÉRENCES compte les articles différents du rayon, UNITÉS additionne les quantités. C'était la question posée sur l'ancienne colonne « quantité ».",
  '28b590f'),
 ('D3', 'Somme = total', "Additionner à la main les valeurs d'achat des lignes et comparer au total rappelé en bas.",
  "La somme des lignes fait EXACTEMENT le total du dépôt.",
  '647702e'),
 ('D4', 'Critères partagés (aller)', "Dans « Liste des articles », chercher un produit présent dans un seul rayon. Puis cliquer « Valorisation par emplacement ».",
  "Seul ce rayon apparaît : la recherche faite dans une vue vaut pour l'autre.",
  '28b590f'),
 ('D5', 'Critères partagés (retour)', "Depuis la vue par emplacement, effacer la recherche et relancer.",
  "La vue par emplacement se met à jour immédiatement et remontre tous les rayons. Les critères restent visibles et modifiables dans les DEUX vues.",
  '28b590f'),
 ('D6', 'Impression', "Cliquer « Imprimer » alors que la vue par emplacement est affichée.",
  "C'est l'édition PAR EMPLACEMENT qui sort (titre « VALORISATION PAR EMPLACEMENT - <dépôt> »), avec les colonnes RÉFÉRENCES et UNITÉS, sa ligne TOTAL, et sa pagination. Le même bouton édite donc ce qui est affiché.",
  '28b590f'),
 ('D7', 'Export Excel', "Regarder le bouton « Exporter Excel » dans la vue par emplacement.",
  "Il est mis en retrait : l'export ne vaut que pour la liste des articles. Il redevient actif en revenant sur celle-ci.",
  '28b590f'),

 ('SECTION', 'E. ONGLET SAISIR VENTE DÉPÔT'),
 ('E1', 'Un seul endroit', "Chercher dans les menus un menu séparé « Vente du dépôt ».",
  "Il n'existe plus : la saisie de vente en dépôt vit uniquement dans cet onglet.",
  'V6.9.48'),
 ('E2', 'Écran complet', "Ouvrir l'onglet et parcourir l'écran.",
  "C'est l'écran de vente complet : type de vente, tiers payants, remises, avoirs, préventes, règlements. L'écran de vente de l'officine n'est pas touché.",
  '4a5bb90'),
 ('E3', 'Dépôt imposé', "Regarder le champ « Dépôt » dans l'onglet de vente.",
  "Il reprend le dépôt choisi en haut de l'écran, en LECTURE SEULE et grisé, mais lisible. Il n'est jamais encadré de rouge : ce n'est plus une saisie, c'est un rappel.",
  '647702e'),
 ('E4', 'Titre', "Lire le titre de l'écran de vente.",
  "Il nomme le dépôt en cours. Si aucun dépôt n'est choisi en haut, le titre n'en nomme AUCUN : il ne garde jamais le nom d'un dépôt précédent.",
  '647702e'),
 ('E5', 'Après une vente validée', "Saisir et valider une vente dans le dépôt.",
  "Le dépôt en cours est CONSERVÉ et reste grisé : il ne disparaît pas, et n'apparaît pas en rouge. Le titre continue de le nommer.",
  'bc094f1'),
 ('E6', 'Stock du dépôt', "Vendre un article, puis vérifier le stock de cet article dans l'onglet Valorisation.",
  "C'est le stock du DÉPÔT qui a baissé, pas celui de l'officine.",
  '82c3055'),
 ('E7', 'On ne vend que ce que le dépôt détient', "Tenter de vendre un article que le dépôt ne détient pas.",
  "La vente est refusée : le dépôt ne peut pas vendre un article qu'il n'a pas.",
  '82c3055'),
 ('E8', 'Où va l\'argent', "Valider une vente en dépôt, puis regarder la caisse de l'opérateur connecté.",
  "L'argent est dans la caisse de l'OPÉRATEUR de l'officine : le chiffre appartient au dépôt, l'encaissement à l'officine.",
  '52da772'),
 ('E9', 'Non-régression officine', "Ouvrir l'écran de vente habituel de l'officine et enchaîner une vente ordinaire.",
  "Rien n'a changé : même écran, même comportement, même stock de l'officine mouvementé.",
  '82c3055'),

 ('SECTION', 'F. ONGLET CHIFFRE D\'AFFAIRES DU DÉPÔT'),
 ('F1', 'Dates du jour', "Ouvrir l'onglet Chiffre d'affaires.",
  "La période part des dates DU JOUR (du jour au jour). Rien n'est chargé tant que la recherche n'est pas lancée, et le bouton Imprimer est inactif.",
  '1ef2bce'),
 ('F2', 'Colonnes demandées', "Lancer une recherche et parcourir les colonnes.",
  "Dans cet ordre : TYPE DE VENTE, MONTANT TTC, MONTANT NET, MARGE, NBRE VENTES, MONTANT ESPÈCES, MONTANT TIERS PAYANT. La colonne « règlement » a disparu (elle n'était jamais renseignée).",
  '1ef2bce'),
 ('F3', 'Ligne TOTAL', "Regarder sous les lignes.",
  "Une ligne TOTAL additionne chaque colonne de montant. Vérifier à la main que le total du net est bien la somme des lignes.",
  '1ef2bce'),
 ('F4', 'Le CA appartient au dépôt', "Jouer une vente dans le dépôt, puis comparer le CA du dépôt et le CA de l'officine sur le même jour.",
  "Le CA du dépôt compte cette vente ; le CA de l'officine ne la compte PAS. Une vente d'officine ordinaire fait l'inverse. Les deux ne se recouvrent jamais.",
  '52da772'),
 ('F5', 'Temps de réponse', "Lancer la recherche sur un jour, puis sur un mois, puis sur un an.",
  "La réponse est immédiate (mesure au banc : 13 à 16 ms). Les 6,85 s signalées le 17/09 étaient une régression, corrigée.",
  '28b590f'),
 ('F6', 'Impression', "Cliquer « Imprimer » après une recherche.",
  "Le PDF s'ouvre dans un onglet. Mêmes colonnes que l'écran, ligne TOTAL, pagination, rappel de la période, et le rappel imprimé que l'argent est dans la caisse de l'opérateur. Les chiffres du PDF sont ceux de l'écran.",
  '1ef2bce'),
 ('F7', 'Période sans vente', "Imprimer sur une période où le dépôt n'a rien vendu.",
  "Le document le DIT (« Ce dépôt n'a enregistré aucune vente sur la période demandée ») au lieu de rendre une page vide.",
  '1ef2bce'),

 ('SECTION', 'G. ONGLET POINT DE CAISSE'),
 ('G1', 'Écran embarqué', "Ouvrir l'onglet Point de caisse.",
  "C'est l'écran « Point Caisse Dépôt » existant, avec ses colonnes (Date/Période, Dépôt, Caissière, Montant Net, Espèces, Crédit) et son total.",
  'd1ec13e'),
 ('G2', 'Même dépôt que les voisins', "Choisir un dépôt en haut de l'écran, puis venir sur l'onglet Point de caisse.",
  "Le dépôt choisi lui est IMPOSÉ et la recherche est relancée : les quatre onglets parlent du même dépôt. Le choix reste modifiable dans l'onglet.",
  'd1ec13e'),
 ('G3', 'Menu d\'origine conservé', "Ouvrir le menu « Point Caisse Dépôt » habituel.",
  "Il fonctionne exactement comme avant : l'onglet ne le remplace pas.",
  'd1ec13e'),

 ('SECTION', 'H. AFFICHAGE — « LA PAGE S\'EST RÉDUITE, LA VUE EST TRONQUÉE »'),
 ('H1', 'Redimensionnement', "Ouvrir n'importe quel écran, puis agrandir et réduire plusieurs fois la fenêtre du navigateur.",
  "Le contenu suit la fenêtre à chaque fois. Aucune bande blanche à droite, aucun écran figé à son ancienne largeur.",
  '7a2b800'),
 ('H2', 'Après un geste ordinaire', "Agrandir la fenêtre, puis lancer une recherche ou ajouter un produit à une vente.",
  "L'écran ne se retracte pas : il garde la largeur de la fenêtre.",
  '7a2b800'),
 ('H3', 'Robustesse', "Enchaîner : ouvrir plusieurs écrans, redimensionner entre chacun, revenir en arrière.",
  "Aucun écran ne reste bloqué à une ancienne taille. Si un incident d'affichage survient malgré tout, il est journalisé dans le Centre de Support (écran Diagnostic / Historique) — ce n'est plus silencieux.",
  '7a2b800'),
 ('H4', 'Écran de vente en onglet', "Ouvrir l'onglet Saisir vente dépôt sur un poste en 1366 px de large.",
  "L'écran de vente est entièrement visible, colonne RÈGLEMENT comprise. Aucun défilement horizontal de la page.",
  '647702e'),

 ('SECTION', 'I. ANALYSE POSOLOGIE (POSOS)'),
 ('I1', 'Menu', "Ouvrir le menu « Analyse Posologie ».",
  "Le menu existe, son libellé est court et tient dans la navigation.",
  '5c13ca8'),
 ('I2', 'Non configuré', "Ouvrir l'écran AVANT d'avoir renseigné posos.properties.",
  "Un bandeau annonce que la passerelle n'est pas configurée et AFFICHE LE CHEMIN EXACT du fichier attendu, en disant s'il est présent.",
  '573c7ee'),
 ('I3', 'Aucun secret exposé', "Renseigner posos.properties, puis appeler api/v1/posos/status depuis le navigateur.",
  "La réponse ne rend que l'adresse, les chemins, l'identifiant MASQUÉ et des booléens. Ni le secret, ni l'identifiant en clair, ni le jeton n'apparaissent — ni ici, ni dans les journaux.",
  '60696a4'),
 ('I4', 'Analyse d\'une ordonnance', "Depuis une vente, demander l'analyse des produits de l'ordonnance.",
  "Les produits sont envoyés PAR LEUR NOM. Les alertes reviennent classées, et une alerte de gravité inconnue est traitée comme MAJEURE — jamais minimisée.",
  '60696a4'),
 ('I5', 'Changement d\'identifiants', "Modifier le secret dans posos.properties, puis relancer une analyse.",
  "Le jeton mémorisé est abandonné et un nouveau est demandé : on ne continue pas avec d'anciens identifiants.",
  '60696a4'),

 ('SECTION', 'J. CLIENTS — CRÉATION STANDARD ET IMPORT'),
 ('J1', 'Création allégée', "Écran des clients : cliquer « Creer client standard ».",
  "La fenêtre ne demande que le nom, les prénoms et le téléphone. Le formulaire complet reste disponible par le bouton « Creer ».",
  '96e4e66'),
 ('J2', 'Entrée enchaîne les champs', "Curseur dans Nom : taper le nom, Entrée ; taper les prénoms, Entrée ; taper le numéro, Entrée.",
  "Entrée passe au champ SUIVANT (nom → prénoms → numéro → bouton Enregistrer), et n'enregistre pas depuis le premier champ.",
  '8acf705'),
 ('J3', 'Le bouton est une étape', "Après la troisième frappe d'Entrée, regarder l'écran sans rien taper.",
  "Le focus est sur Enregistrer, RIEN n'est encore enregistré. Une seconde frappe d'Entrée (ou Espace) enregistre.",
  '8acf705'),
 ('J4', 'Animation de la vente', "Observer le champ actif pendant la saisie, puis le bouton quand le focus l'atteint.",
  "Le champ actif bat comme dans l'écran de vente ; le bouton prend le même battement. Revenir dans un champ éteint le battement du bouton.",
  '8acf705'),
 ('J5', 'Numéro unique', "Créer un second client standard avec un numéro déjà utilisé, y compris écrit autrement (+225 07-08-...).",
  "Refusé, en NOMMANT le client qui détient le numéro, pour qu'on retrouve sa fiche au lieu d'en créer une seconde. Le numéro est enregistré normalisé, sans séparateurs.",
  '96e4e66'),
 ('J6', 'Non-régression assurance', "Créer deux clients NON standards (assurance) avec le même numéro.",
  "Accepté : l'unicité ne porte que sur les clients standards. Deux assurés d'une même famille peuvent partager un numéro.",
  '96e4e66'),
 ('J7', 'Import sous privilège', "Avec un profil SANS P_IMPORT_CLIENTS, ouvrir l'écran des clients.",
  "Les DEUX boutons d'import (« Importer » et « Importer (colonnes au choix) ») sont cachés.",
  '7a2b800'),
 ('J8', 'Import : contrôle serveur', "Sans le privilège, appeler directement les services d'import.",
  "Les deux services refusent : « Votre profil ne permet pas d'importer des clients. »",
  '7a2b800'),
 ('J9', 'Import colonnes au choix', "Avec le privilège : choisir un fichier, lire ses colonnes, désigner nom / prénoms / numéro, contrôler, importer.",
  "Le séparateur est détecté et annoncé ; les colonnes sont pré-désignées d'après les titres même dans un ordre inattendu ; le contrôle n'écrit RIEN et rend un rapport ligne à ligne avec les motifs de rejet ; l'import n'écrit que les lignes retenues.",
  '1856144'),
 ('J10', 'Import : pas de double', "Relancer le même fichier une seconde fois.",
  "Aucune ligne n'est retenue : les numéros sont déjà attribués. Le bouton d'import se désactive après écriture.",
  '1856144'),

 ('SECTION', 'K. STOCK — RAYON, RÉSERVE ET TOTAL'),
 ('K1', 'Trois quantités', "Ouvrir « Etat de stock », puis « Comparaison stock article ».",
  "Les deux écrans affichent le stock RAYON, la RÉSERVE et le TOTAL. Le total est calculé (rayon + réserve) : il ne peut pas se désynchroniser.",
  '5006217'),
 ('K2', 'Masquage des quantités', "Positionner le paramètre AFFICHER_STOCK à « masqué », puis rouvrir les écrans et exporter.",
  "Les trois colonnes sont vides à l'écran ET dans l'export : l'export ne contourne pas le masquage.",
  '5006217'),
 ('K3', 'Édition avec réserve', "Cliquer « Imprimer réserve » dans chacun des deux écrans.",
  "Le PDF s'ouvre dans un onglet, porte les colonnes Rayon / Réserve / Total et leurs valorisations, et rappelle les critères. Les éditions historiques des deux écrans sont conservées à côté.",
  '1ed67f3'),
 ('K4', 'Tri par emplacement', "Éditer sans filtre (tout le catalogue) et parcourir le document.",
  "Les produits sont triés PAR EMPLACEMENT, puis par désignation. Les articles sans emplacement passent en DERNIER. Mesure au banc : 6 753 articles, rayons croissants du premier au dernier.",
  '30a8957'),
 ('K5', 'Pagination', "Aller à la dernière page du même document.",
  "« Page X / Y » sur chaque page (mesure : 158 pages, dernière page « Page 158 / 158 »), avec la date, l'opérateur et le rappel du tri.",
  '30a8957'),
 ('K6', 'Plus de blocage', "Lancer l'édition « Imprimer réserve » de la comparaison d'articles sur tout le catalogue et chronométrer.",
  "Le document sort (mesure : 1,7 s pour l'état de stock, 15,7 s pour la comparaison). Le blocage de 327 s signalé n'existe plus. Note : les 15,7 s restantes viennent de la requête historique de cet écran — chantier à décider.",
  'bc094f1'),

 ('SECTION', 'L. SUGGESTIONS DE RÉAPPRO — ÉCLATER'),
 ('L1', 'Le bouton existe', "Ouvrir « Suggestion de reappro » et regarder la barre d'outils.",
  "Un bouton « ÉCLATER » figure à côté de FUSIONNER.",
  'b27aa4c'),
 ('L2', 'Sans sélection', "Cliquer ÉCLATER sans rien cocher.",
  "Il demande de cocher la suggestion à éclater, et ne fait rien.",
  'b27aa4c'),
 ('L3', 'Une seule à la fois', "Cocher deux suggestions, puis cliquer ÉCLATER.",
  "Refusé : l'éclatement porte sur une suggestion à la fois.",
  'b27aa4c'),
 ('L4', 'Éclatement', "Cocher une suggestion, cliquer ÉCLATER, saisir 3.",
  "Trois suggestions sont obtenues, nommées dans le message avec leur nombre de lignes. Une suggestion de 1 500 lignes donne 3 × 500.",
  'b27aa4c'),
 ('L5', 'Aucune ligne perdue', "Noter le nombre de lignes avant, puis additionner les lignes des morceaux obtenus.",
  "La somme est EXACTEMENT le nombre de départ : aucune ligne perdue, aucune dupliquée. Le reste de la division va aux premiers morceaux (1 501 en 3 → 501 / 500 / 500).",
  'b27aa4c'),
 ('L6', 'Identité conservée', "Retrouver les morceaux dans la liste.",
  "La suggestion de départ GARDE sa référence et devient le premier morceau. Tous les morceaux sont des suggestions MANUELLES, chez le même grossiste que l'originale.",
  'b27aa4c'),
 ('L7', 'Refus explicites', "Essayer : éclater en 1 ; éclater en plus de morceaux qu'il y a de lignes ; éclater une suggestion DÉJÀ COMMANDÉE ; éclater une suggestion vide.",
  "Chaque cas est refusé avec son motif — le nombre de lignes disponibles est rappelé, et la suggestion déjà commandée est nommée. Elle ressort intacte.",
  'b27aa4c'),
 ('L8', 'Non-régression FUSIONNER', "Fusionner deux suggestions du même grossiste.",
  "La fusion fonctionne comme avant.",
  'b27aa4c'),

 ('SECTION', 'M. TICKET Z ET BALANCE'),
 ('M1', 'Ligne « dont vente dépôt »', "Après une vente en dépôt, afficher le ticket Z de l'opérateur.",
  "Une ligne « dont vente dépôt <nom du dépôt> » apparaît, avec son montant.",
  '52da772'),
 ('M2', 'Totaux inchangés', "Comparer le total espèces du ticket Z à la somme des ventes du jour, dépôt comprise.",
  "Le total est INCHANGÉ : la ventilation ne s'ajoute pas au total, elle en fait partie. L'argent du dépôt est bien dans ce tiroir.",
  '52da772'),
 ('M3', 'Temps de réponse', "Afficher le ticket Z sur une journée chargée et chronométrer.",
  "Mesure A/B au banc sur 300 ventes : 3 693 ms avant, 1 489 ms après (1 118 ms à chaud). L'écart se creuse avec le nombre de ventes.",
  '9d214eb'),
 ('M4', 'Balance sans règlement', "Ouvrir la balance sur une période contenant une vente clôturée SANS ligne de règlement.",
  "L'écran s'affiche normalement. La vente compte dans le chiffre d'affaires, mais dans aucun mode de règlement : le total des modes est alors inférieur au net, ce qui est l'information exacte. Avant, l'écran tombait.",
  '9d214eb'),
 ('M5', 'Balance dépôt', "Ouvrir « Balance Depot » et lancer une recherche.",
  "L'écran fonctionne comme avant : les privilèges des onglets de l'écran des dépôts ne l'ont pas touché.",
  'd1ec13e'),

 ('SECTION', 'N. AUTRES POINTS DE L\'ÉVOLUTION 5'),
 ('N1', 'Valorisation archivée', "Vérifier le sous-dossier « valorisations » de la racine de stockage après le 27 du mois.",
  "Un PDF valorisation_<officine>_du_<AAAA-MM-JJ>.pdf y a été produit tout seul à 01:20. Le critère (EMPLACEMENT ou FAMILLE) suit le paramètre KEY_VALORISATION_PDF_CRITERE, et la purge garde 12 mois par défaut.",
  'a245ffe'),
 ('N2', 'Valorisation : écran inchangé', "Produire la valorisation depuis l'écran.",
  "Le document est exactement le même qu'avant : l'archivage est un second appel en lecture seule.",
  'a245ffe'),
 ('N3', 'Ventes supprimées', "Ouvrir l'écran des suppressions de vente.",
  "Une colonne « Vente ouverte par » figure à côté de « Supprimé par », et dans l'export Excel. Pour une suppression automatique de nuit, « Supprimé par » vaut Système et « Vente ouverte par » nomme l'opérateur.",
  '2e61fed'),
 ('N4', 'Règlement carnet dépôt', "Saisir un règlement de carnet dépôt en choisissant une date ANCIENNE (plusieurs semaines).",
  "Deux colonnes distinctes : « Date de reglement » (la date choisie) et « Saisi le » (l'horodatage réel de la saisie). Le dossier, le mouvement de caisse et le ticket restent datés de la date choisie.",
  '75ff1d4'),
 ('N5', 'Articles mouvementés', "Ouvrir « articles mouvementés » et utiliser les trois filtres : mode de mouvement, emplacement, famille.",
  "Une seule ligne par article, même s'il a été vendu puis réapprovisionné ; la colonne « Type(s) de mouvement » concatène les modes. Réinitialiser remet tout à « Tous ».",
  '59e700f'),
 ('N6', 'Inventaire sur toute la liste', "Cliquer « Creer inventaire (toute la liste) » après avoir posé des filtres.",
  "L'inventaire reprend TOUS les articles correspondant aux critères, sans cocher page par page, et son libellé rappelle le mode retenu. Le bouton par sélection est conservé.",
  '59e700f'),
 ('N7', 'Export articles mouvementés', "Cliquer « Exporter Excel ».",
  "L'export répond (il était présenté mais non câblé), emporte les critères de l'écran et porte les trois nouvelles colonnes.",
  '59e700f'),
 ('N8', 'Rattrapage clôtures inventaire', "Lancer le rattrapage des clôtures d'inventaire.",
  "Le traitement fonctionne et son test automatisé est de nouveau en place.",
  'c622289'),
]
